// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Project struct {
	ID        pgtype.UUID        `json:"id"`
	Path      string             `json:"path"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Setting struct {
	Key         string             `json:"key"`
	Value       []byte             `json:"value"`
	IsEncrypted pgtype.Bool        `json:"is_encrypted"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Task struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	Title        string             `json:"title"`
	Status       string             `json:"status"`
	AttemptCount int32              `json:"attempt_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
