// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateProject(ctx context.Context, path string) (Project, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	GetProject(ctx context.Context, path string) (Project, error)
	GetTask(ctx context.Context, id pgtype.UUID) (Task, error)
	IncrementTaskAttempt(ctx context.Context, id pgtype.UUID) (int32, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListTasks(ctx context.Context, projectID pgtype.UUID) ([]Task, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error
}

var _ Querier = (*Queries)(nil)
