// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (path) VALUES ($1) RETURNING id, path, created_at
`

func (q *Queries) CreateProject(ctx context.Context, path string) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, path)
	var i Project
	err := row.Scan(&i.ID, &i.Path, &i.CreatedAt)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, title, status) VALUES ($1, $2, $3) RETURNING id, project_id, title, status, created_at
`

type CreateTaskParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Title     string      `json:"title"`
	Status    string      `json:"status"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.ProjectID, arg.Title, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, path, created_at FROM projects WHERE path = $1 LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, path string) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, path)
	var i Project
	err := row.Scan(&i.ID, &i.Path, &i.CreatedAt)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, project_id, title, status, created_at FROM tasks WHERE project_id = $1
`

func (q *Queries) ListTasks(ctx context.Context, projectID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
